import test from 'node:test';import assert from 'node:assert/strict';import {replay,laboratory} from '../core/research.mjs';import {DEFAULTS} from '../core/engine.mjs';
const meta={symbol:'BTCUSDT',status:'TRADING',contractType:'PERPETUAL',quoteAsset:'USDT',marginAsset:'USDT',baseAsset:'BTC',filters:[{filterType:'MARKET_LOT_SIZE',stepSize:'0.001',minQty:'0.001',maxQty:'100000'},{filterType:'MIN_NOTIONAL',notional:'5'}]};
function data(n=360){return Array.from({length:n},(_,i)=>{const o=100+i*.03+Math.sin(i*.7)*.4,c=o+.05;return {t:1700000100000+i*900000,end:1700000100000+(i+1)*900000-1,o,c,h:c+.3,l:o-.3,v:100+((i%5)*12)};});}
test('Gelecek veri değişikliği geçmiş sonuçları etkilemez',()=>{const rows=data(),a=replay(rows,rows,[],DEFAULTS,meta,{end:220});const changed=rows.map((r,i)=>i>=220?{...r,o:r.o*2,h:r.h*2,l:r.l*2,c:r.c*2}:r);const b=replay(changed,changed,[],DEFAULTS,meta,{end:220});assert.deepEqual(a,b);});
test('Tüm geçmiş test girişleri sonraki mum açılışındadır',()=>{const rows=data(),r=replay(rows,rows,[],{...DEFAULTS,minVotes:2,minScore:80},meta);assert.ok(r.trades>0);for(const t of r.detail){const bar=rows.find(b=>b.t===t.openedAt);const expected=bar.o*(1+t.side*.0001)*(1+t.side*DEFAULTS.slippageBps/10000);assert.ok(Math.abs(t.entry-expected)<1e-8);assert.ok(t.closedAt>t.openedAt);}});
test('Test sonunda açık pozisyon bırakılmaz, tüm net sonuç bakiye ile mutabık',()=>{const rows=data(),r=replay(rows,rows,[],DEFAULTS,meta);assert.ok(Math.abs(r.finalBalance-1000-r.net)<1e-5);});
test('Eksik mumda geçmiş test sessizce devam etmez',()=>{const rows=data();assert.throws(()=>replay(rows.filter((_,i)=>i!==100),rows,[],DEFAULTS,meta));});
test('İleri doğrulamada eğitim daima testten önce; 3 ayrık test penceresi',()=>{const rows=data(),r=laboratory(rows,rows,[],DEFAULTS,meta);assert.equal(r.folds.length,3);r.folds.forEach((f,i)=>{assert.ok(f.trainEnd<f.testStart);if(i)assert.ok(r.folds[i-1].testEnd<f.testStart);});assert.equal(r.contribution.length,4);assert.deepEqual(r.parameters,DEFAULTS);});
test('Laboratuvar kâr korumalı sonucu sabit çıkışla ayrı karşılaştırır',()=>{const rows=data(),r=laboratory(rows,rows,[],DEFAULTS,meta);assert.ok(r.exitComparison);assert.deepEqual(r.exitComparison.protected,r.baseline);assert.equal(typeof r.exitComparison.static.net,'number');});
